### ISSUE TITLE
crash on Android 6.0.1 / Cyanogenmod 13 

### ISSUE THREAD

**Issue by SvenMeyer** [stylo-app/stylo#7] opened 2021-09-30 13:34 UTC
I have some issues with Parity Signer and have been told that a new version will not be available before "end of this year / early next year".

https://github.com/paritytech/parity-signer/issues/833

https://github.com/paritytech/parity-signer/issues/830

@Tbaut Thanks for pointing me to Stylo which looks like as if addresses exactly my problems.

However, I just downloaded the apk 0.9.3 , installed it, and it crashed right away on Android 6.0.1 / Cyanogenmod 13

What can I do ?

**Comment by Tbaut** [comment] 2021-09-30 13:53
Thanks for reporting, the minimal supported SDK version is v23, which is android 6.0 according to https://developer.android.com/studio/releases/platforms so I would expect it to work.

I do my tests on a Android 7 though. I'll take a look and let you know in the next days if I manage to reproduce and get some more info on the origin of the crash.

**Comment by Tbaut** [comment] 2021-09-30 15:57
In the mean time, until I get there, and out of curiosity, could you try and older version, I'd say something like https://github.com/stylo-app/stylo/releases/tag/v0.5.0

The details of the transaction have been brought back from the start, so as long as you're not doing any fancy new extrinsic, we should be able to decode them.

**Comment by Tbaut** [comment] 2021-09-30 19:55
I was able to run the latest on android v6.0 without issue. It's an emulator though since I do not own such a device, but it should be pretty reliable for testing. I'd love to know if you have any issues with other versions you tried. Please also make sure to uninstall any Signer/Stylo version installed before (after making sure you've saved the mnemonic of course).

**Comment by SvenMeyer** [comment] 2021-10-01 07:25
Thanks for looking into this.
I have Parity Signer on the same phone. That shouldn't be a problem - right ?
I have not tried any other versions.
I may try another version (anyone you would suggest?) in the next days or so ... eventually planing to flash a new Android version on that phone anyway.

**Comment by Tbaut** [comment] 2021-10-01 08:30
You're never too sure. They should not use the same key value store, and should not conflict, but who knows. If you have the mnemonic for Signer, better uninstall it.
Android 6 should be fine, I can't tell if this custom Rom is the problem and won't be able to troubleshoot. I did suggest a much older version, the v0.5 for instance.

**Comment by Tbaut** [comment] 2021-11-07 18:09
Closing as I can't reproduce. We can reopen if there's anything new coming up.

**Closed by Tbaut** 2021-11-07 18:09 UTC
